spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beautysalonshifts
    username: root
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#spring:
#  datasource:
#    url: jdbc:h2:mem:database
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#  #      path: /consolah2
#
#  #spring:
#  #  datasource:
#  #    url: jdbc:h2:mem:testdb
#  #    driverClassName : org.h2.Driver
#  #    username: sa
#  #    password:
#
#  jpa:
#    show-sql: true